[app]
name = "ichatgpt"

[app.http]
host = "127.0.0.1"
port = 8888

[chatgpt]
openai_api_key = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
chatgpt_http_proxy = "http://192.168.1.3:7890"
chatgpt_https_proxy = "http://192.168.1.3:7890"
